name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled,
  error and succes states
version: 2.2.0+1
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_builder

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.12.0 <=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  # freezed_annotation: ">=1.0.0 <2.0.0"

dev_dependencies:
  # build_runner: ^2.1.7
  # freezed: ^1.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
