name: async_button_builder
description: A builder to wrap around buttons that handles loading and disabled state
version: 0.0.1-nullsafety.0
homepage: https://github.com/Nolence/async_button_builder

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: