name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled, error and succes states
version: 2.0.2-nullsafety.6
homepage: https://github.com/Nolence/async_button_builder

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.13.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  freezed: ^0.13.0-nullsafety.0
  pedantic: ^1.10.0-nullsafety.3

flutter: