name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled, error and succes states
version: 2.1.1+1
homepage: https://github.com/Nolence/async_button_builder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1
  pedantic: ^1.11.0

flutter: