name: async_button_hook
description: A hook version of async_button_builder which depends on flutter_hooks
version: 0.0.1+4
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_hook

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  async_button_core: ^0.0.1+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
