name: async_button_core
description: Contains the core models and docs for the packages async_button_hook and async_button_builder
version: 0.0.1+5
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.0.3
  freezed: ^0.14.2
  flutter_test:
    sdk: flutter

flutter:
