name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron:  '0 10 * * *'

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.1"
      - name: "Install Tools"
        run: |
          flutter pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Dart Analyze"
        run: |
          melos run analyze
      - name: "Pub Check"
        run: |
          melos run lint:pub

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        channel:
          - dev
          - stable
    steps:
      - name: "Git Checkout"
      - uses: actions/checkout@v2
      - name: "Install Flutter"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - name: "Install Tools"
        run: flutter pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Flutter Test"
        run: melos run test