name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  setup:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@2v

      - name: "Install Flutter"
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

  test:
    timeout-minutes: 15
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
